name: remote_control
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.6
  dio: 5.3.3
  flutter_bloc: 8.1.3
  freezed_annotation: 2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.4.6
  flutter_lints: 2.0.3
  freezed: 2.4.3

flutter:
  uses-material-design: true
