class ShortcutKeys {
  const ShortcutKeys._();

  static const arrowUp = 'up';
  static const arrowDown = 'down';
  static const arrowLeft = 'left';
  static const arrowRight = 'right';

  static const altLeft = 'altleft';
  static const altRight = 'altright';
  static const ctrlLeft = 'ctrlleft';
  static const ctrlRight = 'ctrlright';
  static const shiftLeft = 'shiftleft';
  static const shiftRight = 'shiftright';
  static const backspace = 'backspace';
  static const enter = 'enter';
  static const tab = 'tab';
  static const capsLock = 'capslock';
  static const del = 'del';
  static const end = 'end';
  static const esc = 'esc';
  static const f1 = 'f1';
  static const f2 = 'f2';
  static const f3 = 'f3';
  static const f4 = 'f4';
  static const f5 = 'f5';
  static const f6 = 'f6';
  static const f7 = 'f7';
  static const f8 = 'f8';
  static const f9 = 'f9';
  static const f10 = 'f10';
  static const f11 = 'f11';
  static const f12 = 'f12';
  static const fn = 'fn';
  static const home = 'home';
  static const insert = 'insert';
  static const num0 = 'num0';
  static const num1 = 'num1';
  static const num2 = 'num2';
  static const num3 = 'num3';
  static const num4 = 'num4';
  static const num5 = 'num5';
  static const num6 = 'num6';
  static const num7 = 'num7';
  static const num8 = 'num8';
  static const num9 = 'num9';
  static const numLock = 'numlock';
  static const pageDown = 'pagedown';
  static const pageUp = 'pageup';
  static const pause = 'pause';
  static const printScreen = 'printscreen';
  static const scrollLock = 'scrolllock';
  static const space = 'space';
  static const win = 'win';
}
